name: ${project.name}
main: vg.civcraft.mc.civmenu.CivMenu
version: ${project.version}
author: ['BlackXnt', 'Maxopoly', 'Rourke750', 'suiradx']
depend: [CivModCore]
softdepend: [Mercury]
commands:
  help:
    description: Help command.
    aliases: [help]
    permission: CivMenu.*
    usage: /help plugin
  sign:
    description: Command to sign agreement.
    aliases: [sign]
    permission: CivMenu.*
    usage: /sign
permissions:
    CivMenu.*:
      description: Gives access to /sign and /help
      default: true
